# Generated by Django 5.0.6 on 2024-10-18 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(choices=[('BTECH', 'BTech'), ('MBATECH', 'MBATech')], max_length=10)),
                ('year', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=10)),
                ('sem', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=5)),
                ('subject', models.CharField(choices=[('PPS', 'Programming for Problem Solving'), ('PP', 'Python Programming'), ('ECS', 'Essentials of Computer Science'), ('PEM', 'Principles of Economics and Management'), ('DCCA', 'Digital Circuits and Computer Architecture'), ('CN', 'Computer Networks'), ('DEP', 'Data Extraction and Processing'), ('DSA', 'Data Structures and Algorithms'), ('SE', 'Software Engineering'), ('CD', 'Compiler Design'), ('IVP', 'Image and Video Processing'), ('OS', 'Operating Systems'), ('ADBMS', 'Advanced Database Management Systems'), ('3DP', '3D Printing'), ('DT', 'Drone Technology'), ('EA', 'Elements of Automation'), ('GD', 'Game Design'), ('ML', 'Machine Learning'), ('CNS', 'Cryptography and Network Security'), ('BT', 'Blockchain Technology'), ('NLP', 'Natural Language Processing'), ('BDA', 'Big Data Analytics'), ('PS', 'Probability and Statistics'), ('DLS', 'Digital Logic Design'), ('AI', 'Artificial Intelligence'), ('MAD', 'Mobile Application Development'), ('OR', 'Operation Research'), ('CC', 'Cloud Computing'), ('DL', 'Deep Learning'), ('IOTA', 'IoT and Applications'), ('AWP', 'Advanced Web Programming')], max_length=50)),
                ('exp_no', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=50, unique=True)),
                ('ay', models.CharField(choices=[('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=50)),
                ('term', models.CharField(choices=[('ODD', 'Odd'), ('EVEN', 'Even')], max_length=50)),
                ('exp_file', models.FileField(upload_to='exp_lists/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
