# Generated by Django 5.0.6 on 2024-10-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expLists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='explists',
            unique_together={('programme', 'year', 'sem', 'subject', 'exp_no', 'ay', 'term')},
        ),
    ]
