# Generated by Django 5.0.6 on 2024-10-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expLists', '0002_alter_explists_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='explists',
            unique_together={('subject', 'exp_no', 'ay')},
        ),
    ]
