# Generated by Django 5.0.6 on 2024-10-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expLists', '0003_alter_explists_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explists',
            name='exp_no',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=50),
        ),
    ]
