# Generated by Django 5.0.6 on 2024-10-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expLists', '0004_alter_explists_exp_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='explists',
            unique_together=set(),
        ),
    ]
